### PR TITLE
Changed Grammar

### PR DESCRIPTION
**Pull request by gellatio**
It annoyed me 😡

### CODE REVIEW

**Comment by aerofusionyt** [comment]
Create a new pull request Capitalizing the Some.
Closed.

**Comment by mrdnomaid** [comment]
It's not even incorrect grammar, it's part of the same sentence.

**Comment by aerofusionyt** [comment]
well tom how about you fix it yourself since you have push access

**Comment by mrdnomaid** [comment]
What do you not understand about ***It's not even incorrect***? There was nothing to fix in the first place is what I was trying to say.

**Comment by aerofusionyt** [comment]
it was:
Copyright 2017 NC Network. _s_ome rights reserved.
it should be Copyright 2017 NC Network. Some rights reserved.

**Comment by mrdnomaid** [comment]
No no, he's replaced the comma with a period, which isn't necessary in the first place

**Comment by aerofusionyt** [comment]
It still said some rights reserved instead of Some Rights Reserved. A period is fine.

**Comment by mrdnomaid** [comment]
It said *"**s***ome rights reserved"* because there was a damn comma, which was also just fine. @gellatio's just being pedantic because he needs it **his** way

**Pull request closed without merging**
